<a href="https://colab.research.google.com/github/broskunta/PyTorch-Linear-Regression/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Multiple Linear Regression
Working with multiple inputs.

### Preparation

Import libraries and set the randon seed

In [1]:
#import libraries

from torch import nn
import torch
torch.manual_seed(1)

### Prediction

In [2]:
#set the parameters weight and bias

w = torch.tensor([[2.0], [3.0]], requires_grad= True)
b = torch.tensor([[1.0]], requires_grad= True)

In [4]:
# define the prediction function
def forward(x):
    yhat = torch.mm(x,w) + b #torch.mm supports matrix multiplication
    return yhat

In [5]:
# use the forward function to make a prediction

x = torch.tensor([[1.0, 2.0]])
yhat = forward(x)
print("The result is: ", yhat)

The result is:  tensor([[9.]], grad_fn=<AddBackward0>)


In [6]:
## multiple rows of inputs

X = torch.tensor([[1.0, 1.0], [1.0, 2.0], [1.0, 3.0]])

In [7]:
#make prediction
yhat = forward(X)
print("The result is: ", yhat)

The result is:  tensor([[ 6.],
        [ 9.],
        [12.]], grad_fn=<AddBackward0>)


### Build Custom Modules

In [8]:
# create linear regression
class linear_regression(nn.Module):

    #constructor
    def __init__(self, input_size, output_size):
        super(linear_regression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    # prediction function
    def forward(self, x):
        yhat = self.linear(x)
        return yhat

In [9]:
# make model
model = linear_regression(2,1)

In [10]:
# check the parameters
print("The parameters are: ", list(model.parameters()))

The parameters are:  [Parameter containing:
tensor([[ 0.3643, -0.3121]], requires_grad=True), Parameter containing:
tensor([-0.1371], requires_grad=True)]


In [11]:
# another method
print("The model parameters are: ", model.state_dict())

The model parameters are:  OrderedDict([('linear.weight', tensor([[ 0.3643, -0.3121]])), ('linear.bias', tensor([-0.1371]))])


In [12]:
#make a prediction of x
yhat = model(x)
print("The result is: ", yhat)

The result is:  tensor([[-0.3969]], grad_fn=<AddmmBackward0>)


In [13]:
# make prediction of X
yhat = model(X)
print("The result is: ", yhat)

The result is:  tensor([[-0.0848],
        [-0.3969],
        [-0.7090]], grad_fn=<AddmmBackward0>)


## Practise

In [14]:
# Practice: Build a model to predict the follow tensor.

X = torch.tensor([[11.0, 12.0, 13, 14], [11, 12, 13, 14]])

In [15]:
# make model
model = linear_regression(4,1)

In [16]:
# check the parameters
print("The parameters are: ", list(model.parameters()))

The parameters are:  [Parameter containing:
tensor([[ 0.2347, -0.4707,  0.2999, -0.1029]], requires_grad=True), Parameter containing:
tensor([0.2544], requires_grad=True)]


In [17]:
# another method
print("The model parameters are: ", model.state_dict())

The model parameters are:  OrderedDict([('linear.weight', tensor([[ 0.2347, -0.4707,  0.2999, -0.1029]])), ('linear.bias', tensor([0.2544]))])


In [18]:
# make prediction of X
yhat = model(X)
print("The result is: ", yhat)

The result is:  tensor([[-0.3546],
        [-0.3546]], grad_fn=<AddmmBackward0>)
